install.packages("RAM")
library(RAM)
Webster<-c("intracellular signal transduction",
           "cell adhesion",
           "Rho protein signal transduction",
           "homophilic cell adhesion",
           "chemical synaptic transmission",
           "cell morphogenesis",
           "ion transport",
           "calcium ion-regulated exocytosis",
           "intracellular signal transduction",
           "chemical synaptic transmission",
           "calcium ion transport",
           "semaphorin-plexin signaling pathway",
           "chemical synaptic transmission",
           "ion transport",
           "protein phosphorylation",
           "nervous system development",
           "membrane",
           "plasma membrane",
           "myosin complex",
           "voltage-gated calcium channel...",
           "cell junction",
           "myosin complex",
           "transcription elongation factor complex",
           "postsynaptic membrane",
           "Rho guanyl-nucleotide exchange...",
           "calcium ion binding",
           "ionotropic glutamate receptor activity",
           "clathrin binding",
           "ion channel activity",
           "syntaxin binding",
           "guanyl-nucleotide exchange...",
           "GTPase activator activity",
           "calcium:sodium antiporter activity",
           "semaphorin receptor binding",
           "frizzled binding",
           "protein kinase activity",
           "ATP binding",
           "voltage-gated potassium channel activity",
           "sodium channel activity")
        
Saito<-c("homophilic cell adhesion via plasma membrane adhesion molecules",
         "cell-cell signaling",
         "chemical synaptic transmission",
         "cell-cell adhesion",
         "cell-cell adhesion via plasma-membrane adhesion molecules",
         "anterograde trans-synaptic signaling",
         "synaptic signaling",
         "trans-synaptic signaling",
         "nervous system development",
         "regulation of localization",
         "regulation of transport",
         "synapse part",
         "synapse",
         "postsynaptic membrane",
         "synaptic membrane",
         "plasma membrane region",
         "postsynapse",
         "ionotropic glutamate receptor activity",
         "extracellular ligand-gated ion channel activity",
         "glutamate receptor activity",
         "sulfotransferase activity",
         "ligand-gated ion channel activity",
         "ligand-gated channel activity",
         "transmitter-gated ion channel activity",
         "transmitter-gated channel activity",
         "neurotransmitter receptor activity")

Hansen<-c("signaling",                                                      
       "chemical synaptic transmission",                                 
       "anterograde trans-synaptic signaling",                           
       "synaptic signaling",                                             
       "trans-synaptic signaling",                                       
       "cell communication",                                             
       "signal release",                                                 
       "neurotransmitter secretion",                                     
       "signal release from synapse",                                    
       "synaptic vesicle exocytosis",                                    
       "cell-cell signaling",                                            
       "regulation of biological process",                               
       "signal transduction",                                            
       "cell adhesion",                                                  
       "biological adhesion",                                            
       "homophilic cell adhesion via plasma membrane adhesion molecules",
       "calcium-ion regulated exocytosis",                               
       "regulated exocytosis",                                           
       "cell-cell adhesion via plasma-membrane adhesion molecules",      
       "cell-cell adhesion",                                             
       "regulation of cellular process",                                 
       "cellular response to stimulus",                                  
       "biological regulation",                                          
       "neurotransmitter transport",                                     
       "synaptic vesicle transport",                                     
       "synaptic vesicle localization",                                  
       "establishment of synaptic vesicle localization",                 
       "synaptic vesicle cycle",   
       "ion binding",                                 
       "cation binding",                              
       "metal ion binding",                           
       "adenyl ribonucleotide binding",               
       "calcium ion binding",                         
       "adenyl nucleotide binding",                   
       "metal ion transmembrane transporter activity",
       "ATP binding",                                 
       "gated channel activity",                      
       "ion gated channel activity",                  
       "steroid hormone receptor activity",
       "synapse",                               
       "plasma membrane",                       
       "cell periphery",                        
       "presynapse",                            
       "cell",                                  
       "postsynapse",                           
       "postsynaptic membrane",                 
       "synaptic membrane",                     
       "intrinsic component of plasma membrane")     

group.venn(list(Saito_et.al.=Saito, Hansen=Hansen),label=TRUE, 
           fill = c("lightgrey", "white"),
           cat.pos = c(0, 0),
           lab.cex=0.7)

group.venn(list(Webster_et.al.=Webster, Hansen=Hansen),label=TRUE, 
           fill = c("lightgrey", "white"),
           cat.pos = c(0, 0),
           lab.cex=0.5)

group.venn(list(Saito_et.al.=Saito, Webster_et.al.=Webster, Hansen=Hansen),label=TRUE, 
           fill = c("white", "white","white"),
           cat.pos = c(-10, +10, 180),
           lab.cex=2)
