---
title: "PCA_Crappyfish"
author: "Søren Blikdal Hansen"
date: "6/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Load libraries 

```{r}
library(methylKit)
library(tidyverse)
```

## Load workspace

```{r}
methylkitworkspace<-("/home/sren/Documents/Master_thesis/Crappyfish/methylkit_19samples_10X_MN_210129.RData")
load(methylkitworkspace)
rm(myDiff_MN)
```

## Make design matrix 

```{r}
sample.id <- c("D1","D2","D3","D4","D5","D6","D8","D9","D10", "D11","D12","D13","D14","D15","D16","D17","D18","D19","D20")
treatment_n= c(1,1,1,0,1,0,1,1,0,1,0,1,0,0,1,0,0,1,0)
treatment<-gsub(1,"sick",treatment) %>% gsub("0","healthy",.)
design.matrix<-bind_cols(ID=sample.id, treatment=treatment)
```

## Make and plot PCA 
You can also embed plots, for example:

```{r PCA}
pca <- percMethylation(meth.filtered) %>% t(.) %>% prcomp(.,center=T, scale. = F)
percent_variance_pca<-summary(pca)$importance["Proportion of Variance",] * 100
pca_plot<-as_tibble(pca$x) %>% bind_cols(design.matrix)
ggplot(pca_plot,aes(x=PC1, y=PC2, color=treatment,label= ID)) +
geom_point() +
ggrepel::geom_text_repel() +
xlab(label = paste("PC1 (", percent_variance_pca[1], "percent of the total va
riance)")) +
ylab(label = paste("PC2 (", percent_variance_pca[2], "percent of the total va
riance)"))+ggtitle("Crappyfish PCA 10X")
```
