#!/bin/bash

### PBS Job Batch Options
### Note: No commands may be executed until after the #PBS lines
### Account information
#PBS -W group_list=ku-cbd -A ku-cbd
### Job name (comment out the next line to get the name of the script used as the job name)
##PBS -N 20_samples_methylKit_11Dec20
### Output files (comment out the next 2 lines to get the job name used instead)
##PBS -e 20_samples_methylKit_21Dec20.err
##PBS -o 20_samples_methylKit_21Dec20.log
### Only send mail when job is aborted or terminates abnormally
#PBS -m abe
#PBS -M soren.blikdal.hansen@sund.ku.dk 
### Number of nodes
#PBS -l nodes=1:ppn=40:thinnode
### Memory
#PBS -l mem=180gb
### Requesting time - format is <days>:<hours>:<minutes>:<seconds> (here, 12 hours)
#PBS -l walltime=24:00:00
### Add current shell environment to job (comment out if not needed)
#PBS -V
### Forward X11 connection (comment out if not needed)
###PBS -X

### Script below ###

module load tools 
module load gcc/8.2.0
module load intel/perflibs/2020_update2
module load R/4.0.3 
module load openssl/1.1.1b

Rscript /home/projects/ku-cbd/data/HoloFish/morten_fish/Epigenome/Novogene_CrappyFish_20samples_24Sep20_Analyses/Methylkit_19samples_5X_MN_210129.R

# get stats
qstat -f $PBS_JOBID
